apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: dzdk52y6c-nodejs 
  janus-idp.io/tekton: dzdk52y6c-nodejs
  backstage.io/kubernetes-id: dzdk52y6c-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dzdk52y6c-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  